version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ccamp-net

  redis:
    image: redis:7
    networks:
      - ccamp-net

  backend:
    build: ../backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:

networks:
  ccamp-net: